### ISSUE TITLE
JSON::ParserError al tratar de procesar una respuesta de servidor no disponible

### ISSUE THREAD

**Issue by e3matheus** [open-pay/openpay-ruby#14]
Parece que cuando regresan una respuesta de servidor no disponible(Ayer ocurrieron varias entre las 5 y las 8pm), el json que devuelve el servidor no lo puede interpretar y devuelve esta excepción:

JSON::ParserError: A JSON text must at least contain two octets!

vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:155 in initialize
vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:155 in new
vendor/bundle/ruby/2.0.0/gems/json-1.8.2/lib/json/common.rb:155 in parse
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/errors/openpay_exception.rb:13 in initialize
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/errors/openpay_exception_factory.rb:43 in new
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/errors/openpay_exception_factory.rb:43 in create
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/open_pay_resource.rb:157 in rescue in post
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/open_pay_resource.rb:138 in post
vendor/bundle/ruby/2.0.0/gems/openpay-1.0.7/lib/openpay/charges.rb:88 in create

**Comment by darkaz** [comment]
Todas las respuesta que regresa Openpay son JSON y la librería esta preparada para leer ese tipo de respuestas. Mas bien lo que paso es que no le esta llegando el JSON como tal. Nos puedes pasar el log de la petición por correo a soporte@openpay.mx por favor para revisar que sucedió

**Comment by e3matheus** [comment]
Muy bien. Ayer les envie un correo con algunas peticiones de ejemplo. Quedo
atento a su respuesta.
