### ISSUE TITLE
Problema al iniciar servicios de API

### ISSUE THREAD

**Issue by vickcx** [open-pay/openpay-ruby#19]
Que tal, estoy tratando de iniciar con los servicios de OpenPay, pero estoy recibiendo constemente el siguiente error:

2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- openpay (LoadError)

Utilizo Ruby version 2.3.1 Y Rails 4

Muchas gracias

**Comment by jemy-dasm-openpay** [comment]
Cerramos este issue por la antigüedad del mismo.
En caso de que aun persistieran los problemas podríamos reabrirlo para su revisión.

¡Saludos!
