### ISSUE TITLE
'Please specify a valid source_id' en pagos con tarjetas guardadas

### ISSUE THREAD

**Issue by danielavilac** [open-pay/openpay-ruby#21]
Estoy tratando de hacer un cargo a la tarjeta guardada de un cliente. El cliente ya lo tengo guardado y también una tarjeta.
Cuando consulto las tarjetas de mi cliente (en modo sandbox) obtengo mi tarjeta:
```
[{"id"=>"k4xfvbu1x3uoqqbrfuj0",
  "type"=>"debit",
  "brand"=>"visa",
  "address"=>
   {"line1"=>"Av 5 de Febrero",
    "line2"=>"Roble 207",
    "line3"=>"",
    "state"=>"Queretaro",
    "city"=>"Queretaro",
    "postal_code"=>"76900",
    "country_code"=>"MX"},
  "card_number"=>"411111XXXXXX1111",
  "holder_name"=>"Juan Perez Ramirez",
  "expiration_year"=>"20",
  "expiration_month"=>"12",
  "allows_charges"=>true,
  "allows_payouts"=>true,
  "creation_date"=>"2018-10-14T21:19:43-05:00",
  "bank_name"=>"Banamex",
  "customer_id"=>"alzchegsfqp5odgg9dmj",
  "bank_code"=>"002"}]
```
Como se puede ver tengo la tarjeta con `id`: `k4xfvbu1x3uoqqbrfuj0` guardada en OpenPay, al tratar de hacer un cargo a esa tarjeta como dice la documentación me pide un `source_id` el cual de acuerdo a la documentación se describe como:

> **string** (requerido, longitud = 45) 
ID de la tarjeta guardada o el id del token creado de donde se retirarán los fondos.

Entiendo que puede usarse el ID de la tarjeta (o sea `k4xfvbu1x3uoqqbrfuj0`) o bien el `token`, estoy utilizando el ID debido a que el token se uso solo para guardar la tarjeta.

Al ejecutar el método `@charges.create(request_hash)` como se indica en la documentación me regresa el error: `Please specify a valid source_id`

NOTA: También vi que el la documentación hace mención a lo siguiente:

> Si desea crear un cliente y llevar un historial de sus cargos consulte como crear un cliente y realice el cargo a nivel cliente.

Pero nunca encontré como hacer el cargo a nivel cliente explícitamente en la documentación, me parece que "hacer el cargo a nivel cliente" es justamente lo que estoy haciendo.

Agradezco cualquier ayuda.

**Comment by Monoradioactivo** [comment]
@danielavilac Te está marcando ese error debido a que estás tratando de hacer un cargo a nivel comercio:
`@charges.create(request_hash)`
Lo que tú necesitas es hacer un cargo a nivel cliente ya que la tarjeta ya la tienes asignada a un cliente, sólo es cuestión de pasar el customer_id:
`@charges.create(request_hash, customer_id)`

**Comment by ronniebermejo** [comment]
Este spec puede ilustrar/guiarte: https://github.com/open-pay/openpay-ruby/blob/cdafeca6b6af5338c1129568ce32fae00deab8b9/test/spec/charges_spec.rb#L50

**Comment by braulio123bv** [comment]
estoy haciendo esto         
$charge = $openpay->charges->create($chargeData,$id_userOpenPay);
pero no me soluciona el problema, alguna ayuda ??

**Comment by Nahtanoj2** [comment]
> estoy haciendo esto
> $charge = $openpay->charges->create($chargeData,$id_userOpenPay);
> pero no me soluciona el problema, alguna ayuda ??

Hola @braulio123bv No sé si todavía tengas problema con la implementación pero justamente estaba buscando una solución para el problema.

Lo que estás enviando es código PHP, pero este es el repositorio para Ruby.

Por suerte, mi problema también era para PHP y encontré la solución. 
Si lo que deseas es hacer un cargo a un cliente previamente guardado lo que tienes que hacer es obtener los datos del cliente y con el mismo objeto generas el cargo.

`$customer =  $openpay->customers->get( $cliente_id );`
`$customer->charges->create($chargeData);`

**Comment by Luermuma** [comment]
Cuando usas un cargo a nivel de cliente ósea usando el id del cliente en  charges ->create("id",$data) debes de asegurarte que en $data no vaya ningún dato del cliente.

**Comment by siliconsocket** [comment]
Yo también tenía el mismo problema, en mi caso con NodeJS, pero descubrí que a un costado en la documentación indican los dos casos (comercio y cliente).

![Captura de Pantalla 2020-03-31 a la(s) 5 00 45 p m](https://user-images.githubusercontent.com/57454123/78082867-47b89800-7371-11ea-91ed-94b8455b2284.png)
